/* =========================================================================
   New Bharat Trading Company — catalog data
   -------------------------------------------------------------------------
   THIS IS THE ONE FILE YOU EDIT to change site info, products and prices.
   Everything on the site (products page, category pages, product pages,
   enquiry buttons) is generated from the data below.

   Prices are INDICATIVE list prices in INR per 100 pieces, exclusive of GST,
   transcribed from our current price list (w.e.f. 1 April 2026) and subject
   to change. Final pricing is always confirmed on enquiry.
   ========================================================================= */

/* ---- 1. Your business details (drive every Enquire / Call button) ------- */
const SITE = {
  name:    "New Bharat Trading Company",
  short:   "New Bharat Trading Co.",
  tagline: "Industrial Fasteners & Bearings · Authorised Dealer & Stockist",
  email:   "nbtcoindia@gmail.com",
    phone:   "+91 98678 33131",
  whatsapp:"919867833131",
  address: "107, 2nd Floor, Nagdevi Street, Nagdevi, Mumbai – 400003, Maharashtra",
  hours:   "Mon–Sat · Open until 7:00 PM",
  estd:    "1996",
};

/* ---- 2. Categories ------------------------------------------------------ */
const CATEGORIES = [
  { slug: "socket-screws", no: "01", name: "Socket Screws",
    blurb: "Cap, countersunk, low-head, shoulder, button-head and set screws in 12.9 alloy steel.",
    img: "assets/pd-socket-head-cap-screw.jpg" },
  { slug: "hex-fasteners", no: "02", name: "Hex Bolts, Nuts & Washers",
    blurb: "High-tensile hex bolts, hex & nylock nuts and spring washers to DIN / ISO / IS.",
    img: "assets/pd-hex-head-bolt-10-9.jpg" },
  { slug: "durlok", no: "03", name: "Durlok® Self-Locking",
    blurb: "Vibration-resistant self-locking bolts, nuts and washers — Durlok® self-locking system.",
    img: "assets/pd-wedge-lock-washer.jpg" },
  { slug: "construction", no: "04", name: "Construction Fasteners",
    blurb: "IS 3757 high-strength structural bolt assemblies, anchors and CE-approved range.",
    img: "assets/pd-structural-bolt-assembly.jpg" },
  { slug: "petrochemical", no: "05", name: "Petrochemical Fasteners",
    blurb: "ASTM A193 B7 stud bolts and A194 2H heavy hex nuts for flanged joints.",
    img: "assets/pd-stud-bolt-a193-b7.jpg" },
  { slug: "stainless-steel", no: "06", name: "Stainless Steel Fasteners",
    blurb: "SS 304 and SS 316 hex bolts, nuts, washers, studs and machine screws for corrosion-resistant service.",
    img: "assets/pd-ss-hex-bolt.jpg" },
  { slug: "machine-screws", no: "07", name: "Machine and Self-Tapping Screws",
    blurb: "Phillips pan and countersunk machine screws, plus self-tapping and self-drilling screws for sheet metal.",
    img: "assets/pd-self-drilling-screw.jpg" },
];

/* ---- 3. Products -------------------------------------------------------- */
/* Each price row: { size, price } — price = INR / 100 pcs, ex-GST (indicative) */
const PRODUCTS = [
  /* ---------------- SOCKET SCREWS ---------------- */
  {
    slug: "socket-head-cap-screw",
    name: "Socket Head Cap Screw (SHCS)",
    category: "socket-screws",
    featured: true,
    img: "assets/pd-socket-head-cap-screw.jpg",
    standard: "DIN 912 · ISO 4762 · IS 2269",
    grade: "Property Class 12.9",
    material: "High-grade alloy steel",
    sizeRange: "M2 – M42",
    lengthRange: "3 – 300 mm",
    finish: "Black thermal (self-colour); HDG / electro-galv on request",
    blurb: "The benchmark high-tensile cap screw — deep accurate socket, compound fillet radius and wide-radius threads for maximum fatigue life. The workhorse of machine building.",
    specs: [
      { k: "Head marking", v: "U130 / 12.9" },
      { k: "Thread", v: "ISO metric coarse, 5g6g" },
      { k: "Wrench", v: "Hexagon (Allen) key" },
      { k: "Conforms to", v: "IS 1367 / ISO 898-1" },
    ],
    prices: [
      { size: "M6 × 20", price: "423" },
      { size: "M8 × 25", price: "920" },
      { size: "M10 × 30", price: "1,313" },
      { size: "M12 × 40", price: "3,145" },
      { size: "M16 × 50", price: "6,933" },
      { size: "M20 × 60", price: "17,763" },
    ],
  },
  {
    slug: "countersunk-socket-cap-screw",
    name: "Countersunk Socket Cap Screw (CSK)",
    category: "socket-screws",
    featured: false,
    img: "assets/pd-countersunk-socket-cap-screw.jpg",
    standard: "DIN 7991 · ISO 10642 · IS 6761",
    grade: "Property Class 12.9",
    material: "High-grade alloy steel",
    sizeRange: "M3 – M24",
    lengthRange: "6 – 130 mm",
    finish: "Black thermal; HDG / electro-galv on request",
    blurb: "Flat 90° head sits flush with the surface — for clean, snag-free assemblies where a protruding head can't be tolerated. Fully threaded across the range.",
    specs: [
      { k: "Head", v: "Countersunk 90°, internal hex" },
      { k: "Thread", v: "ISO metric, 5g6g" },
      { k: "Conforms to", v: "IS 1367 / ISO 898-1" },
      { k: "Note", v: "All sizes fully threaded" },
    ],
    prices: [
      { size: "M4 × 12", price: "668" },
      { size: "M5 × 16", price: "737" },
      { size: "M6 × 20", price: "819" },
      { size: "M8 × 25", price: "1,202" },
      { size: "M10 × 30", price: "2,057" },
      { size: "M12 × 40", price: "3,166" },
    ],
  },
  {
    slug: "socket-low-head-cap-screw",
    name: "Socket Low Head Cap Screw (LHCS)",
    category: "socket-screws",
    featured: false,
    img: "assets/bolt.png",
    standard: "DIN 7984 · ASME B18.3.1M",
    grade: "Property Class 10.9",
    material: "High-grade alloy steel",
    sizeRange: "M4 – M20",
    lengthRange: "8 – 100 mm",
    finish: "Black thermal; HDG / electro-galv on request",
    blurb: "Reduced head height for tight clearances and shallow counterbores where a standard cap screw head simply won't fit.",
    specs: [
      { k: "Head", v: "Low profile, internal hex" },
      { k: "Thread", v: "ISO metric coarse, 5g6g" },
      { k: "Conforms to", v: "IS 1367 / ISO 898-1" },
    ],
    prices: [
      { size: "M4 × 8", price: "1,166" },
      { size: "M5 × 16", price: "824" },
      { size: "M6 × 16", price: "798" },
      { size: "M8 × 20", price: "966" },
      { size: "M10 × 25", price: "1,628" },
      { size: "M12 × 30", price: "3,162" },
    ],
  },
  {
    slug: "socket-set-screw",
    name: "Socket Set Screw (Grub Screw)",
    category: "socket-screws",
    featured: false,
    img: "assets/bolt.png",
    standard: "DIN 913–916 · ISO 4026–4029 · IS 6094",
    grade: "Property Class 45H",
    material: "High-grade alloy steel",
    sizeRange: "M3 – M20",
    lengthRange: "3 – 65 mm",
    finish: "Black thermal; HDG / electro-galv on request",
    blurb: "Headless grub screws with knurled cup point for locating and securing collars, gears and pulleys onto shafts. Cone, dog and flat points available.",
    specs: [
      { k: "Point", v: "Knurled cup (standard)" },
      { k: "Other points", v: "Flat · cone · dog / half-dog (+25%)" },
      { k: "Thread", v: "ISO metric, 5g6g" },
      { k: "Conforms to", v: "IS 1367 / ISO 898-5" },
    ],
    prices: [
      { size: "M3 × 6", price: "237" },
      { size: "M4 × 6", price: "251" },
      { size: "M5 × 8", price: "316" },
      { size: "M6 × 10", price: "406" },
      { size: "M8 × 12", price: "461" },
      { size: "M10 × 16", price: "638" },
    ],
  },
  {
    slug: "button-head-socket-screw",
    name: "Button Head Socket Screw",
    category: "socket-screws",
    featured: false,
    img: "assets/pd-button-head-socket-screw.jpg",
    standard: "ISO 7380 · DIN EN ISO 7380",
    grade: "Property Class 10.9",
    material: "High-grade alloy steel",
    sizeRange: "M3 – M16",
    lengthRange: "6 – 60 mm",
    finish: "Black thermal; HDG / electro-galv on request",
    blurb: "Domed decorative head with a wide bearing surface — a finished look for covers, panels and guards where appearance matters.",
    specs: [
      { k: "Head", v: "Domed button, internal hex" },
      { k: "Thread", v: "ISO metric coarse, 5g6g" },
      { k: "Conforms to", v: "IS 1367 / ISO 898-1" },
    ],
    prices: [
      { size: "M4 × 8", price: "742" },
      { size: "M5 × 10", price: "773" },
      { size: "M6 × 12", price: "847" },
      { size: "M8 × 16", price: "1,224" },
      { size: "M10 × 20", price: "2,166" },
      { size: "M12 × 25", price: "3,432" },
    ],
  },
  {
    slug: "socket-head-shoulder-screw",
    name: "Socket Head Shoulder Screw",
    category: "socket-screws",
    featured: false,
    img: "assets/pd-socket-head-shoulder-screw.jpg",
    standard: "ISO 7379 · BS 4168 · DIN 9841",
    grade: "Property Class 12.9",
    material: "High-grade alloy steel",
    sizeRange: "M5 – M20 thread (Ø6 – Ø24 shoulder)",
    lengthRange: "10 – 120 mm",
    finish: "Black thermal; HDG / electro-galv on request",
    blurb: "Precision-ground shoulder (h8) acts as a dowel, bearing axle or pivot — the go-to part for linkages, jigs and moving assemblies.",
    specs: [
      { k: "Shoulder tol.", v: "Precision ground to h8" },
      { k: "Spec method", v: "Quote shoulder Ø + thread, e.g. Ø16 (M12)" },
      { k: "Thread class", v: "5g6g" },
      { k: "Conforms to", v: "ISO 898-1 (12.9)" },
    ],
    prices: [
      { size: "Ø6 (M5) × 10", price: "4,890" },
      { size: "Ø8 (M6) × 16", price: "6,134" },
      { size: "Ø10 (M8) × 20", price: "8,537" },
      { size: "Ø12 (M10) × 30", price: "9,987" },
      { size: "Ø16 (M12) × 40", price: "20,779" },
      { size: "Ø20 (M16) × 50", price: "57,000" },
    ],
  },

  /* ---------------- HEX BOLTS, NUTS & WASHERS ---------------- */
  {
    slug: "hex-head-bolt-10-9",
    name: "10.9 Hex Head Bolt",
    category: "hex-fasteners",
    featured: true,
    img: "assets/pd-hex-head-bolt-10-9.jpg",
    standard: "DIN 931 / 933 · IS 1364",
    grade: "Property Class 10.9",
    material: "Boron / alloy steel",
    sizeRange: "M4 – M48",
    lengthRange: "10 – 300 mm",
    finish: "Black thermal; HDG / electro-galv on request",
    blurb: "High-tensile hex bolt — half and full thread — for structural and machinery joints. Supplied with matching nuts and washers from stock.",
    specs: [
      { k: "Tensile", v: "1040 N/mm² (10.9)" },
      { k: "Thread", v: "ISO metric coarse" },
      { k: "Standards", v: "DIN 931 (half) / 933 (full)" },
      { k: "Conforms to", v: "IS 1364 / ISO 898-1" },
    ],
    prices: [
      { size: "M8 × 25", price: "—" },
      { size: "M10 × 30", price: "—" },
      { size: "M12 × 40", price: "—" },
      { size: "M16 × 50", price: "—" },
      { size: "M20 × 60", price: "—" },
      { size: "M24 × 80", price: "—" },
    ],
  },
  {
    slug: "hex-nut-iso-4032",
    name: "Hex Nut (ISO 4032)",
    category: "hex-fasteners",
    featured: true,
    img: "assets/pd-hex-nut-iso-4032.jpg",
    standard: "ISO 4032 · DIN 934 · IS 1364",
    grade: "Class 8 / 10",
    material: "Carbon / alloy steel",
    sizeRange: "M6 – M72",
    lengthRange: "—",
    finish: "Black thermal; HDG / electro-galv on request",
    blurb: "Standard metric hex nut to pair with 8.8 and 10.9 bolts. Heavy hex, lock, dome and coupling nuts also available from stock.",
    specs: [
      { k: "Property class", v: "8 / 10" },
      { k: "Thread", v: "ISO metric coarse" },
      { k: "Standards", v: "ISO 4032 / DIN 934" },
      { k: "Conforms to", v: "IS 1367" },
    ],
    prices: [
      { size: "M8", price: "—" },
      { size: "M10", price: "—" },
      { size: "M12", price: "—" },
      { size: "M16", price: "—" },
      { size: "M20", price: "—" },
      { size: "M24", price: "—" },
    ],
  },
  {
    slug: "nylock-nut",
    name: "Nylock Nut (Nylon Insert)",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-nylock-nut.jpg",
    standard: "DIN 985 · ISO 7040",
    grade: "Grade 8 / 10",
    material: "Carbon / alloy steel + nylon ring",
    sizeRange: "M3 – M39",
    lengthRange: "—",
    finish: "Zinc plated / HDG on request",
    blurb: "Prevailing-torque nut with a nylon insert that grips the thread and resists loosening under vibration — no spring washer required.",
    specs: [
      { k: "Locking", v: "Nylon insert ring" },
      { k: "Grade", v: "8 / 10" },
      { k: "Standards", v: "DIN 985 / ISO 7040" },
      { k: "All-metal type", v: "DIN 980M/V available" },
    ],
    prices: [
      { size: "M6", price: "—" },
      { size: "M8", price: "—" },
      { size: "M10", price: "—" },
      { size: "M12", price: "—" },
      { size: "M16", price: "—" },
      { size: "M20", price: "—" },
    ],
  },
  {
    slug: "spring-washer",
    name: "Spring Washer",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-spring-washer.jpg",
    standard: "DIN 127B · DIN 7980 · IS 3063",
    grade: "Spring steel",
    material: "Hardened spring steel",
    sizeRange: "M3 – M39",
    lengthRange: "—",
    finish: "Bright / zinc plated",
    blurb: "Split spring washer that maintains tension under the nut to resist loosening. Flat-section (DIN 127B) and square-section (DIN 7980) types in stock, plus hardened and structural washers.",
    specs: [
      { k: "Section", v: "Flat (127B) / square (7980)" },
      { k: "Material", v: "Hardened spring steel" },
      { k: "Also stocked", v: "Plain, hardened & structural washers" },
      { k: "Conforms to", v: "DIN 127B / IS 3063" },
    ],
    prices: [
      { size: "M6", price: "—" },
      { size: "M8", price: "—" },
      { size: "M10", price: "—" },
      { size: "M12", price: "—" },
      { size: "M16", price: "—" },
      { size: "M20", price: "—" },
    ],
  },

  /* ---------------- DURLOK ---------------- */
  {
    slug: "durlok-self-locking-bolt",
    name: "Durlok® Self-Locking Bolt",
    category: "durlok",
    featured: false,
    img: "assets/bolt.png",
    standard: "Durlok® self-locking system",
    grade: "Property Class 10.9 / 12.9",
    material: "High-grade alloy steel",
    sizeRange: "M5 – M24",
    lengthRange: "On request",
    finish: "Self-colour / coated",
    blurb: "Durlok's ring of serrations under the head bites into the joint face to deliver outstanding vibration resistance without a separate locking element. Matching Durlok nuts and washers complete the system.",
    specs: [
      { k: "Locking", v: "Serrated bearing face" },
      { k: "System", v: "Durlok bolt + nut + washer" },
      { k: "Grade", v: "10.9 / 12.9" },
      { k: "Best for", v: "High-vibration joints" },
    ],
    prices: [
      { size: "M8", price: "—" },
      { size: "M10", price: "—" },
      { size: "M12", price: "—" },
      { size: "M16", price: "—" },
      { size: "M20", price: "—" },
    ],
  },

  /* ---------------- CONSTRUCTION ---------------- */
  {
    slug: "structural-bolt-assembly",
    name: "IS 3757 Structural Bolt Assembly",
    category: "construction",
    featured: true,
    img: "assets/pd-structural-bolt-assembly.jpg",
    standard: "IS 3757 / IS 6623 / IS 6649",
    grade: "Class 10.9S (8.8S also)",
    material: "High-strength structural steel",
    sizeRange: "M16 – M30",
    lengthRange: "40 – 300 mm",
    finish: "Self-colour / HDG",
    blurb: "Complete high-strength friction-grip assembly — IS 3757 bolt, IS 6623 nut and IS 6649 hardened washer — for steel structures, bridges and plant. TCB and DTI options available.",
    specs: [
      { k: "Bolt", v: "IS 3757 · 8.8S / 10.9S" },
      { k: "Nut", v: "IS 6623 · 8S / 10S" },
      { k: "Washer", v: "IS 6649 hardened" },
      { k: "Also", v: "Tension-control (TCB) & DTI to BS EN 14399" },
    ],
    prices: [
      { size: "M16 × 50", price: "—" },
      { size: "M20 × 60", price: "—" },
      { size: "M24 × 75", price: "—" },
      { size: "M27 × 80", price: "—" },
      { size: "M30 × 90", price: "—" },
    ],
  },

  /* ---------------- PETROCHEMICAL ---------------- */
  {
    slug: "stud-bolt-a193-b7",
    name: "Stud Bolt with 2 Heavy Hex Nuts",
    category: "petrochemical",
    featured: false,
    img: "assets/pd-stud-bolt-a193-b7.jpg",
    standard: "ASTM A193 B7 · A194 2H",
    grade: "B7 stud / 2H nut",
    material: "Alloy steel (chromoly)",
    sizeRange: "M12 – M56 · 1/2\" – 2-1/4\"",
    lengthRange: "60 – 500 mm",
    finish: "Black / PTFE / Xylan / HDG",
    blurb: "Fully-threaded stud bolts with two heavy hex nuts for flanged joints in petrochemical, refinery and power applications. Supplied to ASTM A193 B7 with A194 2H nuts.",
    specs: [
      { k: "Stud", v: "ASTM A193 Gr. B7" },
      { k: "Nuts", v: "ASTM A194 Gr. 2H (×2)" },
      { k: "Coatings", v: "PTFE / Xylan / Geomet on request" },
      { k: "Threads", v: "Metric or UNC (BSW/UNF on request)" },
    ],
    prices: [
      { size: "M16 × 90", price: "—" },
      { size: "M20 × 110", price: "—" },
      { size: "M24 × 130", price: "—" },
      { size: "M30 × 160", price: "—" },
      { size: "M36 × 200", price: "—" },
    ],
  },
  {
    slug: "copper-washer",
    name: "Copper Sealing Washer",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-copper-washer.jpg",
    standard: "DIN 7603 / IS 2016",
    grade: "—",
    material: "Pure copper",
    sizeRange: "M5 to M30",
    lengthRange: "—",
    finish: "Bright copper",
    blurb: "Soft copper crush washer that conforms under load to give a leak-tight metal seal on hydraulic, fuel and oil fittings.",
    specs: [ { k: "Type", v: "Solid crush / sealing" }, { k: "Material", v: "Electrolytic copper" } ],
    prices: [ { size: "M8", price: "—" }, { size: "M10", price: "—" }, { size: "M12", price: "—" }, { size: "M16", price: "—" } ],
  },
  {
    slug: "dome-nut",
    name: "Dome Nut (Cap Nut)",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-dome-nut.jpg",
    standard: "DIN 1587 / IS 2687",
    grade: "Class 6 / 8",
    material: "Carbon steel, zinc-plated",
    sizeRange: "M4 to M24",
    lengthRange: "—",
    finish: "Yellow / white zinc",
    blurb: "Domed cap nut that covers the bolt thread for a clean, safe, finished appearance while protecting the thread end.",
    specs: [ { k: "Head", v: "Closed hex dome" }, { k: "Thread", v: "ISO metric coarse" } ],
    prices: [ { size: "M6", price: "—" }, { size: "M8", price: "—" }, { size: "M10", price: "—" }, { size: "M12", price: "—" } ],
  },
  {
    slug: "coupling-bolt",
    name: "High-Tensile Coupling Bolt",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-coupling-bolt.jpg",
    standard: "DIN 931 / 933",
    grade: "Class 8.8 / 10.9",
    material: "Alloy / carbon steel",
    sizeRange: "M8 to M36",
    lengthRange: "30 to 300 mm",
    finish: "Black / zinc / HDG",
    blurb: "High-tensile coupling bolt for joining shafts, flanges and structural members where a strong shear connection is required.",
    specs: [ { k: "Grade", v: "8.8 / 10.9" }, { k: "Thread", v: "ISO metric coarse" } ],
    prices: [ { size: "M12 x 60", price: "—" }, { size: "M16 x 80", price: "—" }, { size: "M20 x 100", price: "—" } ],
  },
  {
    slug: "square-head-bolt",
    name: "High-Tensile Square Head Bolt",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-square-head-bolt.jpg",
    standard: "DIN 478 / 479",
    grade: "Class 8.8",
    material: "Carbon / alloy steel",
    sizeRange: "M8 to M30",
    lengthRange: "25 to 200 mm",
    finish: "Black oxide / zinc",
    blurb: "Square-head bolt that grips in a slot or against a face so it can be tightened from one side, common on machinery and jigs.",
    specs: [ { k: "Head", v: "Square" }, { k: "Grade", v: "8.8" } ],
    prices: [ { size: "M10 x 40", price: "—" }, { size: "M12 x 50", price: "—" }, { size: "M16 x 65", price: "—" } ],
  },
  {
    slug: "plain-washer",
    name: "Plain Washer (Flat)",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-plain-washer.jpg",
    standard: "DIN 125 / ISO 7089 / IS 2016",
    grade: "200 HV",
    material: "Carbon steel",
    sizeRange: "M3 to M64",
    lengthRange: "—",
    finish: "Zinc / black / HDG",
    blurb: "General-purpose flat washer that spreads the clamp load and protects the joint surface under the nut or bolt head.",
    specs: [ { k: "Type", v: "Flat, Form A" }, { k: "Hardness", v: "200 HV" } ],
    prices: [ { size: "M8", price: "—" }, { size: "M10", price: "—" }, { size: "M12", price: "—" }, { size: "M16", price: "—" } ],
  },
  {
    slug: "hex-set-screw",
    name: "High-Tensile Hex Set Screw (Fully Threaded)",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-hex-set-screw.jpg",
    standard: "DIN 933 / ISO 4017",
    grade: "Class 8.8 / 10.9",
    material: "Carbon / alloy steel",
    sizeRange: "M4 to M36",
    lengthRange: "6 to 200 mm",
    finish: "Zinc / black",
    blurb: "Fully-threaded hex bolt (set screw) for through-holes and tapped blind holes where thread engagement is needed along the full length.",
    specs: [ { k: "Thread", v: "Full length" }, { k: "Grade", v: "8.8 / 10.9" } ],
    prices: [ { size: "M8 x 25", price: "—" }, { size: "M10 x 30", price: "—" }, { size: "M12 x 40", price: "—" } ],
  },
  {
    slug: "heavy-hex-nut",
    name: "Heavy Hex Nut",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-heavy-hex-nut.jpg",
    standard: "DIN 934 / ASME B18.2.2",
    grade: "Class 8 / 10",
    material: "Carbon / alloy steel",
    sizeRange: "M8 to M48",
    lengthRange: "—",
    finish: "Black / zinc / HDG",
    blurb: "Thicker, wider heavy hex nut for high-clamp-load and structural joints where a standard nut would be over-stressed.",
    specs: [ { k: "Type", v: "Heavy hex" }, { k: "Class", v: "8 / 10" } ],
    prices: [ { size: "M12", price: "—" }, { size: "M16", price: "—" }, { size: "M20", price: "—" }, { size: "M24", price: "—" } ],
  },
  {
    slug: "punched-plain-washer",
    name: "Punched Plain Washer",
    category: "hex-fasteners",
    featured: false,
    img: "assets/pd-punched-plain-washer.jpg",
    standard: "IS 2016 / DIN 126",
    grade: "—",
    material: "Carbon steel",
    sizeRange: "M5 to M39",
    lengthRange: "—",
    finish: "Zinc / black",
    blurb: "Commercial punched flat washer for general assembly and load distribution where a close-tolerance washer is not required.",
    specs: [ { k: "Type", v: "Punched flat" }, { k: "Tolerance", v: "Commercial" } ],
    prices: [ { size: "M8", price: "—" }, { size: "M10", price: "—" }, { size: "M12", price: "—" } ],
  },
  {
    slug: "prevailing-torque-nut",
    name: "Prevailing Torque Lock Nut (All-Metal)",
    category: "durlok",
    featured: false,
    img: "assets/pd-prevailing-torque-nut.jpg",
    standard: "DIN 980 / IS 7002",
    grade: "Class 8 / 10",
    material: "Carbon steel, zinc-plated",
    sizeRange: "M5 to M36",
    lengthRange: "—",
    finish: "White / yellow zinc",
    blurb: "All-metal self-locking nut with a deformed thread crown that resists loosening from vibration, with no nylon insert so it suits high temperatures.",
    specs: [ { k: "Locking", v: "All-metal prevailing torque" }, { k: "Temp", v: "High-temperature capable" } ],
    prices: [ { size: "M8", price: "—" }, { size: "M10", price: "—" }, { size: "M12", price: "—" }, { size: "M16", price: "—" } ],
  },
  {
    slug: "wedge-lock-washer",
    name: "Wedge-Lock Washer Pair",
    category: "durlok",
    featured: false,
    img: "assets/pd-wedge-lock-washer.jpg",
    standard: "—",
    grade: "—",
    material: "Hardened steel / SS",
    sizeRange: "M6 to M36",
    lengthRange: "—",
    finish: "Delta protect / SS",
    blurb: "Pair of wedge-lock washers that lock by tension, not friction; the cam faces rise more than the thread pitch, so the joint cannot vibrate loose.",
    specs: [ { k: "Action", v: "Tension / wedge locking" }, { k: "Supply", v: "Bonded pairs" } ],
    prices: [ { size: "M10", price: "—" }, { size: "M12", price: "—" }, { size: "M16", price: "—" }, { size: "M20", price: "—" } ],
  },
  {
    slug: "threaded-stud-full",
    name: "Fully-Threaded Stud / Threaded Rod",
    category: "petrochemical",
    featured: false,
    img: "assets/pd-threaded-stud-full.jpg",
    standard: "ASTM A193 B7 / DIN 976",
    grade: "B7 / Class 8.8",
    material: "Alloy / carbon steel",
    sizeRange: "M6 to M56",
    lengthRange: "cut to length",
    finish: "Black / PTFE / HDG",
    blurb: "Continuously-threaded stud, cut to length on request, for flanged joints, anchoring and general fabrication.",
    specs: [ { k: "Thread", v: "Continuous / full" }, { k: "Grade", v: "B7 / 8.8" } ],
    prices: [ { size: "M12", price: "—" }, { size: "M16", price: "—" }, { size: "M20", price: "—" }, { size: "M24", price: "—" } ],
  },
  {
    slug: "ss-hex-bolt",
    name: "Stainless Steel Hex Bolt",
    category: "stainless-steel",
    featured: false,
    img: "assets/pd-ss-hex-bolt.jpg",
    standard: "DIN 931 / 933 / ISO 4014",
    grade: "A2-70 / A4-80",
    material: "SS 304 / SS 316",
    sizeRange: "M4 to M30",
    lengthRange: "10 to 200 mm",
    finish: "Self-colour (passivated)",
    blurb: "Corrosion-resistant stainless hex bolt for marine, chemical, food and outdoor use, in SS 304 (A2) and SS 316 (A4).",
    specs: [ { k: "Grade", v: "A2-70 / A4-80" }, { k: "Material", v: "SS 304 / SS 316" } ],
    prices: [ { size: "M8 x 25", price: "—" }, { size: "M10 x 30", price: "—" }, { size: "M12 x 40", price: "—" } ],
  },
  {
    slug: "ss-hex-nut",
    name: "Stainless Steel Hex Nut",
    category: "stainless-steel",
    featured: false,
    img: "assets/pd-ss-hex-nut.jpg",
    standard: "DIN 934 / ISO 4032",
    grade: "A2-70 / A4-80",
    material: "SS 304 / SS 316",
    sizeRange: "M3 to M30",
    lengthRange: "—",
    finish: "Self-colour (passivated)",
    blurb: "Stainless hex nut to match SS bolts and studs for corrosion-resistant joints, in SS 304 and SS 316.",
    specs: [ { k: "Grade", v: "A2-70 / A4-80" }, { k: "Material", v: "SS 304 / SS 316" } ],
    prices: [ { size: "M8", price: "—" }, { size: "M10", price: "—" }, { size: "M12", price: "—" }, { size: "M16", price: "—" } ],
  },
  {
    slug: "ss-plain-washer",
    name: "Stainless Steel Plain Washer",
    category: "stainless-steel",
    featured: false,
    img: "assets/pd-ss-plain-washer.jpg",
    standard: "DIN 125 / ISO 7089",
    grade: "A2 / A4",
    material: "SS 304 / SS 316",
    sizeRange: "M3 to M30",
    lengthRange: "—",
    finish: "Self-colour",
    blurb: "Stainless flat washer that spreads load and resists corrosion, matching SS bolts and nuts.",
    specs: [ { k: "Type", v: "Flat, Form A" }, { k: "Material", v: "SS 304 / SS 316" } ],
    prices: [ { size: "M8", price: "—" }, { size: "M10", price: "—" }, { size: "M12", price: "—" } ],
  },
  {
    slug: "ss-spring-washer",
    name: "Stainless Steel Spring Washer",
    category: "stainless-steel",
    featured: false,
    img: "assets/pd-ss-spring-washer.jpg",
    standard: "DIN 127 / IS 3063",
    grade: "A2 / A4",
    material: "SS 304 / SS 316",
    sizeRange: "M3 to M24",
    lengthRange: "—",
    finish: "Self-colour",
    blurb: "Stainless split spring washer that maintains tension and resists loosening in corrosive environments.",
    specs: [ { k: "Type", v: "Split spring" }, { k: "Material", v: "SS 304 / SS 316" } ],
    prices: [ { size: "M8", price: "—" }, { size: "M10", price: "—" }, { size: "M12", price: "—" } ],
  },
  {
    slug: "ss-stud",
    name: "Stainless Steel Stud Bolt",
    category: "stainless-steel",
    featured: false,
    img: "assets/pd-ss-stud.jpg",
    standard: "ASTM A193 B8 / B8M",
    grade: "B8 / B8M",
    material: "SS 304 / SS 316",
    sizeRange: "M6 to M42",
    lengthRange: "cut to length",
    finish: "Self-colour",
    blurb: "Stainless fully-threaded stud for corrosion-resistant flanged joints, A193 B8 (304) and B8M (316).",
    specs: [ { k: "Grade", v: "B8 / B8M" }, { k: "Material", v: "SS 304 / SS 316" } ],
    prices: [ { size: "M12", price: "—" }, { size: "M16", price: "—" }, { size: "M20", price: "—" } ],
  },
  {
    slug: "csk-philips-self-tapping",
    name: "Countersunk Phillips Self-Tapping Screw",
    category: "machine-screws",
    featured: false,
    img: "assets/pd-csk-philips-self-tapping.jpg",
    standard: "DIN 7982 / IS 7168",
    grade: "—",
    material: "Carbon steel",
    sizeRange: "No.4 to No.14",
    lengthRange: "6 to 75 mm",
    finish: "Yellow zinc",
    blurb: "Countersunk Phillips self-tapping screw (AB type) that cuts its own thread in sheet metal, plastic and wood for a flush finish.",
    specs: [ { k: "Head", v: "Countersunk Phillips" }, { k: "Type", v: "AB self-tapping" } ],
    prices: [ { size: "No.8 x 25", price: "—" }, { size: "No.10 x 32", price: "—" }, { size: "No.12 x 38", price: "—" } ],
  },
  {
    slug: "ss-csk-philips-self-tapping",
    name: "Stainless Steel CSK Phillips Self-Tapping Screw",
    category: "machine-screws",
    featured: false,
    img: "assets/pd-ss-csk-philips-self-tapping.jpg",
    standard: "DIN 7982",
    grade: "A2 / A4",
    material: "SS 304 / SS 316",
    sizeRange: "No.4 to No.14",
    lengthRange: "6 to 75 mm",
    finish: "Self-colour",
    blurb: "Stainless countersunk Phillips self-tapping screw (AB type) for corrosion-resistant fixing into sheet, plastic and timber.",
    specs: [ { k: "Head", v: "Countersunk Phillips" }, { k: "Material", v: "SS 304 / SS 316" } ],
    prices: [ { size: "No.8 x 25", price: "—" }, { size: "No.10 x 32", price: "—" } ],
  },
  {
    slug: "ss-csk-philips-machine",
    name: "Stainless Steel CSK Phillips Machine Screw",
    category: "machine-screws",
    featured: false,
    img: "assets/pd-ss-csk-philips-machine.jpg",
    standard: "DIN 965 / ISO 7046",
    grade: "A2 / A4",
    material: "SS 304 / SS 316",
    sizeRange: "M2 to M10",
    lengthRange: "4 to 60 mm",
    finish: "Self-colour",
    blurb: "Stainless countersunk Phillips machine screw for tapped holes and nuts where a flush head is required.",
    specs: [ { k: "Head", v: "Countersunk Phillips" }, { k: "Material", v: "SS 304 / SS 316" } ],
    prices: [ { size: "M4 x 12", price: "—" }, { size: "M5 x 16", price: "—" }, { size: "M6 x 20", price: "—" } ],
  },
  {
    slug: "ss-pan-philips-machine",
    name: "Stainless Steel Pan Phillips Machine Screw",
    category: "machine-screws",
    featured: false,
    img: "assets/pd-ss-pan-philips-machine.jpg",
    standard: "DIN 7985 / ISO 7045",
    grade: "A2 / A4",
    material: "SS 304 / SS 316",
    sizeRange: "M2 to M10",
    lengthRange: "4 to 60 mm",
    finish: "Self-colour",
    blurb: "Stainless pan-head Phillips machine screw for general enclosure, panel and electrical assembly work.",
    specs: [ { k: "Head", v: "Pan Phillips" }, { k: "Material", v: "SS 304 / SS 316" } ],
    prices: [ { size: "M3 x 10", price: "—" }, { size: "M4 x 12", price: "—" }, { size: "M5 x 16", price: "—" } ],
  },
  {
    slug: "self-drilling-screw",
    name: "Self-Drilling Screw (Hex Washer Head, TEK)",
    category: "machine-screws",
    featured: false,
    img: "assets/pd-self-drilling-screw.jpg",
    standard: "DIN 7504 / IS 15487",
    grade: "—",
    material: "Carbon steel, hardened",
    sizeRange: "No.8 to No.14",
    lengthRange: "13 to 100 mm",
    finish: "Zinc / bonded washer",
    blurb: "Self-drilling (TEK) screw with hex washer head and bonded sealing washer that drills and taps its own hole in sheet metal and cladding in one pass.",
    specs: [ { k: "Point", v: "Self-drilling" }, { k: "Head", v: "Hex washer + bonded washer" } ],
    prices: [ { size: "No.10 x 25", price: "—" }, { size: "No.12 x 32", price: "—" }, { size: "No.14 x 50", price: "—" } ],
  },
];

/* expose for the browser */
window.SITE = SITE;
window.CATEGORIES = CATEGORIES;
window.PRODUCTS = PRODUCTS;
